class AppSettings:
    CONFIDENCE_REJECTION_THRESHOLD = 0.40
    BUTTERWORTH_LOW_FREQ_DEFAULT = 2500.0
    BUTTERWORTH_HIGH_FREQ_DEFAULT = 9000.0
    BUTTERWORTH_ORDER_DEFAULT = 4
    FFT_POINTS_DEFAULT = 4096
